#!/usr/bin/python3
import sys,os
if os.path.dirname(sys.argv[0])==".":
    raise Exception("Please run this script from the parent directory.")
sys.path+=[".", "./sim/"]

import requests, re
from time import sleep

#
# API call based on js get request sent by
# https://fallenlondon.fandom.com/wiki/Special:ListUsers

url="https://fallenlondon.wiki/w/api.php"

params={"action":"query",
        "format":"json",
        "prop":"revisions",
        "rvslots":"*",
#        "rvprop":"content",
        "formatversion":"2",
         }
session=requests.Session()

import sys, re
import parsing
from functions import *
actions={}
fname="lists/_gen_linkable_actions.txt"
if True:
    f=open(fname, "w")
    f.close()
f=open(fname, "w")

parsing.read_all_actions(actions, {}, {})
f.write("# autogenerated by %s, do not edit\n#\n"%sys.argv[0])

for a in sorted(actions.keys()):
    try:
        if a.startswith("Buy at") or a.startswith("Sell at")\
           or a.startswith("Get Choice:"):
            continue
        print(a)
        sleep(1)
        params["titles"]=a
        reply=session.get(url, params=params).json()["query"]["pages"][0]
        if "missing" in reply:
            print("'%s' is not found on the wiki"% a)
        elif "pageid" in reply:
            print("'%s' is on the wiki"% a)
            f.write("%s\n"%a)
        else:
            print("This reply confused me: %s"%reply)
    except Exception as e:
        raise Exception("Error for item %s (line='%s'):"%(i, l)) from e
        continue
